CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(50) UNIQUE NOT NULL,
                                     password VARCHAR(255) NOT NULL,
                                     email VARCHAR(100) UNIQUE NOT NULL,
                                     role VARCHAR(20) NOT NULL,
                                     enabled BOOLEAN DEFAULT true,
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bank_cards (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          card_number_encrypted VARCHAR(255) NOT NULL,
                                          card_number_masked VARCHAR(19) NOT NULL,
                                          card_holder VARCHAR(100) NOT NULL,
                                          expiry_date DATE NOT NULL,
                                          cvv_encrypted VARCHAR(255) NOT NULL,
                                          status VARCHAR(20) NOT NULL,
                                          balance DECIMAL(15, 2) DEFAULT 0.00,
                                          user_id BIGINT,
                                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS card_transactions (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 from_card_id BIGINT NOT NULL,
                                                 to_card_id BIGINT NOT NULL,
                                                 amount DECIMAL(15, 2) NOT NULL,
                                                 status VARCHAR(20) NOT NULL,
                                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                 FOREIGN KEY (from_card_id) REFERENCES bank_cards(id) ON DELETE CASCADE,
                                                 FOREIGN KEY (to_card_id) REFERENCES bank_cards(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id BIGINT,
                                          action VARCHAR(50) NOT NULL,
                                          entity_type VARCHAR(50),
                                          entity_id BIGINT,
                                          description TEXT,
                                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);